config/routes.rb
Rails.application.routes.draw do
  resources :costs
  devise_for :users

  root 'home#index'

    

    resources :incomes

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :costs
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  validates :amount, presence: true
  validates :amount, :numericality => { :greater_than_or_equal_to => 0, :message => 'should be positive numerical value' }
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user
  validates :amount, presence: true
  validates :amount, :numericality => { :greater_than_or_equal_to => 0, :message => 'should be positive numerical value' }
  validates :limit, :numericality => { :greater_than_or_equal_to => 0, :message => 'should be positive numerical value' } 
  validates :limit, :numericality => { :less_than_or_equal_to => :amount, :message => 'should be lesser than INCOME value' }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :costs
  has_one :income
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:edit, :update]
 
  def index
    @costs = current_user.costs
  end

  def new
    @cost = Cost.new
  end
  
  def edit
  end
 
  def create
    @cost = Cost.new(cost_params)
    @cost.user_id = current_user.id
    @cost.category_id = params[:categories]
    respond_to do |format|
      if @cost.save
        format.html { redirect_to costs_path, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    
    def set_cost
      @cost = Cost.find(params[:id])
    end

    def cost_params
      params.require(:cost).permit(:amount, :category_id, :user_id, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:edit, :update]
  
  def new
   @income = Income.new
  end

  def edit
  end

  def create
    @income = Income.new(income_params)
    @income.user_id = current_user.id
    respond_to do |format|
      if @income.save
        format.html { redirect_to root_path, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to root_path, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

private
    def set_income
      @income = Income.find(params[:id])
    end

    def income_params
      params.require(:income).permit(:amount,:limit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost,:html => {:class => "form-horizontal center"}) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :category %><br>
    <%= select_tag "categories", options_from_collection_for_select(Category.all, "id", "name") %>
  </div>
  <div class="field">
    <%= f.label :amount %>*<br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :description %>
  </div><br>
  <div class="actions">
    <%= f.submit 'SUBMIT', :class => 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Expenses</h2>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Amount Spent</th>
      <th>Expense Category</th>
      <th>Expense Description</th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.amount %></td>
        <td><%= Category.where('id=?',cost.category_id).first.try(:name) %></td>
        
        <td><%= cost.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Enter Your Expense', new_cost_path, :class => 'btn btn-primary btn-sm' %>

app/views/costs/new.html.erb
<h2>New Expense</h2>

<%= render 'form' %>

app/views/incomes/_form.html.erb
<br>
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
     

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Amount %><br>
    <%= f.text_field :amount %>&nbsp;<b>$</b>
  </div>
<br>
  <div class="field">
    <%= f.label :Expenses_Limit %><br>
    <%= f.text_field :limit %>&nbsp;<b>$</b>
  </div>
   <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<%= render 'form' %>

app/views/incomes/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet-2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style>
body
{
color:black;
}
</style>
<body background="http://www.planwallpaper.com/static/images/518079-background-hd.jpg">
<div class="container">
<div class="masthead">
        
        <nav>
          <ul class="nav nav-justified">
            <li class="active"><a href="/">Home</a></li>
            <%if current_user %><li><a href="/costs">Expenses</a></li><%end%>
            <li><%= render 'users/menu/registration_items' %></li>
            <li><%= render 'users/menu/login_items' %></li>
          </ul>
        </nav>
      </div>
<% if current_user %>
<br><div style="width:90%;color:white;font-weight:bold">
<% @income_total = current_user.income.amount if current_user.income.present?%>
<div style="float:left;">Your Income Amount: <b><%= @income_total.present? ? @income_total : '0 '%>$</b></div>
<% @expenses_total = current_user.costs.map(&:amount).sum unless current_user.costs.blank?%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expenses Total: <%= @expenses_total.present? ? @expenses_total : '0 '%>$
<% if @expenses_total.present? %>
<div style="float:right">Savings($): <%= @income_total - @expenses_total unless @income_total.blank? || @expenses_total.blank?%></div></div>
<% end %>
<% if @expenses_total.blank? %>
<div style="float:right">Savings($): <%= @income_total unless @income_total.blank? %></div></div>
<% end %>
<% if current_user.income.present? && current_user.income.limit.present? && @expenses_total.present? %>
<% if @expenses_total > current_user.income.limit %>
 <div style="color:red;">Your expenses have exceeded from LIMIT-<%= current_user.income.limit %></div>
<% end %>
<% end %>
<%elsif controller_name == 'home'%>
<br><br><center>
<%= image_tag 'wallet.jpg', :style => 'border-radius: 30px 30px 30px 30px;'%><br><br>
<h1 style="color:white">My Wallet</h1></center> 
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
 
<% else %>

  <%= link_to('Login', new_user_session_path)  %>  
 
<% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <% if current_user.income.present? %>
  <%= link_to('Update Income', edit_income_path(current_user.income.id)) %>
  <% else %>
  <%= link_to('Update Income', new_income_path) %>
  <% end %>
<% else %>
  
  <%= link_to('Register', new_user_registration_path)  %>
  
<% end %>